name: "Refresh"
on:
  push:
    branches:
      - main
    paths:
      - 'config/ftbquests/**'
  workflow_dispatch:
  
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create branch & Checkout
        run: |
          branch_name=${GITHUB_SHA::7}
          if [[ -n "$(git ls-remote origin $branch_name 2>/dev/null)" ]]; then
            echo "branch ${branch_name} already exists"
            exit -3
          else
            git checkout -b "${branch_name}"
            git push origin "${branch_name}"
          fi
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python deps
        run: pip install -r .github/localization/requirements.txt

      - name: Generate Translate Keys
        run: python .github/localization/ftbquest_localization.py

      - name: Generate Traditional Translate Keys
        run: python .github/localization/chinese_converter.py

      - name: Make packwiz executable
        run: chmod +x .github/packwiz

      - name: Packwiz Refresh
        run: .github/packwiz refresh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Quest Localization & Refresh

      - name: Push branch
        run: git push origin "${GITHUB_SHA::7}"
        
      - name: Open Pull Request
        run:  gh pr create --base main --head ${GITHUB_SHA::7} --title "Update Quest Localization" --body "Automated localization update"
